branches:
  except:
    - /^travis\/.*/
language: node_js
cache:
  directories:
    - "node_modules"
os:
  - linux
# Windows is not supported at all. Bummer.
# Testing on OS X makes no sense, when everything is tested on linux and in browsers
jobs:
  include:
    # stage test
    - node_js: '6' # npm test
    - node_js: '8' # npm test
    - node_js: '10' # npm test
    # stage tag
    - stage: tag
      node_js: '8'
      install: skip
      script:
        - scripts/travisGithubTag.sh
